package com.anupam.java.tries.simple;

import com.anupam.java.tries.simple.Trie.Node;

import java.util.List;


/**
 * TODO: Insert description here. (generated by anupams)
 */
public class TrieManager {

  private static final String FILE_PATH =
      "/usr/local/google/home/anupams/beltway-workspace_22APril/SomethingCreative/words/wordsList";

  public static void main(String args[]) {
    List<String> words = TrieGenerator.readWords(FILE_PATH);
    Trie trie = new Trie();
    Node root = new Node();
    TrieGenerator.populateTrie(trie, root, FILE_PATH);
    System.out.println(root);
    System.out.println(trie.searchWord(root, "anupam"));
    System.out.println(trie.searchWord(root, "bastards"));
    System.out.println(trie.searchWord(root, "ba$tards"));
  }
}
