package com.anupam.rhyme.tries;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.Test;

/**
 * TODO: Insert description here. (generated by anupams)
 */
public class UtilTest {

  /**
   * @throws Exception
   */
  @Before
  public void setUp() throws Exception {}

  @Test
  public void testCompareKeys() {
    assertEquals(4, Util.getMatchingCharacterCount("test", "test"));
    assertEquals(0, Util.getMatchingCharacterCount("", ""));
    assertEquals(0, Util.getMatchingCharacterCount("test", "fest"));
    assertEquals(2, Util.getMatchingCharacterCount("test", "text"));
    assertEquals(0, Util.getMatchingCharacterCount("", "text"));
    assertEquals(1, Util.getMatchingCharacterCount("t1", "text"));
  }

}
